language: node_js

node_js:
  - "7"

script: npm run build

before_deploy:
  pip install --user awscli

deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://aws-website-dojo-j25vf --region=us-east-1 --delete
  skip_cleanup: true
